version: 2

models:
  - name: trip_distance_avg
    description: "A starter dbt model"
    columns:
      - name: trip_month
        description: "The primary key for this table"
        tests:
          - unique

  - name: trip_distance_avg
    description: "A starter dbt model"
    columns:
      - name: trip_year
        description: "The primary key for this table"
        tests:
          - unique

  - name: trip_distance_avg
    description: "A starter dbt model"
    columns:
      - name: avg_trip_distance
        description: "The primary key for this table"
        tests:
          - unique
